Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, PropertyValidation.m
Fixes #8. Tested in VSCode.
**Before**
**After**
**After with theme from https://github.com/Gimly/vscode-matlab/issues/89**
=> Add handling for property validation

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, argumentValidation.m
Adds support for function argument validation addressing #13 and https://github.com/Gimly/vscode-matlab/issues/90. See screenshot below for vscode highlighting of test file. Also tested in Atom.
```matlab
function argumentValidation(x,~,v,method,flag, opts)
% Comment before arguments blocks
arguments
% Block comment
x (1,:) {mustBeNumeric,mustBeReal} % trailing coment
~
% Line comment
v (1,:) {mustBeNumeric,mustBeReal, mustBeEqualSize(v,x)}
method (1,:) char {mustBeMember(method,{'linear','cubic','spline'})} = 'linear' % End of line comment
% End block comment
end
arguments (Repeating)
% Trailing flags
flag (1,:) string {mustBeMember(flag,["first","second","third"])}
end
arguments
opts.Named (1,:) string {mustBeNumeric(opts.Named), ... Dotdotdot comment
mustBeReal}
end
end
```
**VSCode …
=> Syntax highlighting for arguments block and improvements for property validation

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, PropertyValidation.m
Fixes #16 and #15. Tested in vscode and atom.
**Before**
**After**
=> Fix property comments after semicolon and multi-line classdef

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, controlFlow.m
This fixes #19. Tested in VSCode and Atom with various files.
**Before**
**After**
=> Allow block start and end patterns to occur on lines with other code

Account.m, CircleArea.m, Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage
Fixes #24   Tested in VSCode and Atom
**Before**
**After**
=> Fix comment highlighting after properties|events|methods|enumeration block headers

Account.m, Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, controlFlow.m, lineContinuations.m
Fixes #18 #19 and #23 Tested in vscode and atom.
=> Support line continuations in parens and brackets

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage
```matlab
classdef MyClass % A comment
end
```
doesn't highlight the comment properly. This fixes that.
Tested in vscode and atom.
**before**
**after**
=> Classdef line comment highlighting

.travis.yml
Set up and tested on my fork. My PR seems to have run in Travis so there may be no extra config needed other than this file. See the "All checks have passed" section below
The test builds of my fork are at:
https://travis-ci.com/rlivings39/MATLAB-Language-grammar
including a build where I injected the same bug from #32 to verify that it fails the build:
https://travis-ci.com/rlivings39/MATLAB-Language-grammar/builds/146682462
=> Travis xmllint test for grammar file

.vscode/settings.json, Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, package.json, test/snap/Account.m.snap, test/snap/AnEnum.m.snap, test/snap/CircleArea.m.snap, test/snap/PropertyValidation.m.snap, test/snap/argumentValidation.m.snap, test/t16CommentAfterClassdefBlockMembers.m
Fix import module highlighting and make keyword control end tokens consistent with Microsoft convention.
CLA signed per https://github.com/mathworks/MATLAB-Language-grammar/pull/37#issuecomment-847052613.
=> Fix import module and `varargin{:}` highlighting

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/snap/Account.m.snap
Workaround for meta scoping being broken on matrix or cell assignments.
This will also prevent broken scoping from appearing in the VS Code extension and its language service.
=> Limit single variable assignments to structs and variables

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage
Resolves #70
Also the pattern can be simplified to not include the entire grammar, but only #variables to resolve for `nargin`, `varargin`, etc.
=> simplify indexing_curly_brackets

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t41FunctionDefinitions.m
This PR fixes #72, when function definitions are declared on multiple lines. 
I will add comments in every change of the tmLanguage describing why is is required. 
The PR adds scope checks and additional cases to the existing test *test/t41FunctionDefinitions.m*
Due to the nature of the per-line matching behavior of the textmate language grammar, and the almost unrestricted usage of MATLAB's line continuation operator `...`, it is impossible to differentiate between:
1. Function with no output argument and input argument declaration including parenthesis on new line: 
```matlab
function funcNoOutputParensOnNewLine ...
(inputArg)
disp(inputArg);
end
```
2. Function with a single output argument without brackets and equals sign on new line:
```matlab
function outputArg ... 
= …
```
=> Fixes for multiple function definitions

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t51Imports.m
Imports with leading whitespaces are not recognized as import, but`#command-dual` key with token `meta.function-call.command.matlab.
=> Import with leading whitespace

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/snap/Account.m.snap, test/snap/controlFlow.m.snap, test/t78EOLcommentsInBlocks.m
The `meta.elseif.matlab` and `meta.else.matlab` scopes only detected for the `elseif` and `else` keywords. This is due to both scopes using the *match* rule, while it should be using *begin/end* instead. The patterns in the match rule are never used as a *match* rule does not support patterns. 
Also fixes #78 and while declarations are recognized. 
Additionally, better support for line continuations including comments in multiline declarations.
=> Fix elseif and else meta blocks

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t54LineContinuationInAnonymousFunctions.m, test/t57Operators.m, test/t61ReadWriteOperations.m, test/t80AnonymousFunctionArgument.m
Fixes #80 
Anonymous functions are currently defined to end on `;` or comment. This does now allow for declaring anonymous function directly as argument to a function.
=> Anonymous functions as arguments

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/snap/controlFlow.m.snap, test/t19SingleLineBlocks.m, test/t64SwitchStatements.m
Fixes #45
Fixes #47
Fixes #52
Fixes #64
Switch statements are syntactically the same as if/elseif/else.
| switch                | if                   |
|-----------------------|----------------------|
| `switch` keyword      | `if` keyword         |
| switch declaration    | if declaration       |
| -                     | if statements        |
| `case` keyword        | `elseif` keyword     |
| case declaration      | elseif declaration   |
| case statements       | elseif statements    |
| `otherwise` keyword   | `else` keyword       |
| otherwise statements  | else statements      |
| `end` keyword         | `end` keyword        |
This PR copies the implementation from #82 and replaces the tokens with the ones for switch.
=> fix switch statements

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t87ClassAttributes.m
Resolves #87 
This still is not entirely correct however it fails only in the case where the end of the attribute block is separated by newline (and line continuation) from the `ClassName`. Making a fully correct TextMate compatible grammar seems impossible due to the ability to arbitrarily place line continuations, however this is a closer approximation and improves the usability of this grammar for further machine interaction e.g. https://github.com/sphinx-contrib/matlabdomain
Note: #86 must go in first.
=> Fix broken attribute parsing in classdef.

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t89MetaclassLiterals.m
Add functionality to correctly identify `?namespace.class` metaclass references everywhere.
Resolves #89
=> Correct metaclass parsing

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/t93ContinuationAfterClassAttributes.m
This change resolves tokenization in the following case by allowing a line continuation to follow the attributes:
```matlab
classdef (Abstract) ...
ClassName
end
```
Fixes #93
=> Fix grammar when there is a line continuation after class attributes

Matlab.tmbundle/Syntaxes/MATLAB.tmLanguage, test/snap/Account.m.snap, test/snap/PropertyValidation.m.snap, test/snap/controlFlow.m.snap, test/snap/lineContinuations.m.snap, test/t08PropertyValidation.m, test/t95AttributeParsing.m
This extends the work in #88 to also improve parsing of `property`, `events`, and `methods` blocks.
WIP until tests are updated.
=> fixed attribute parsing in properties methods and events
